name: run-tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.2, 8.1, 8.0]
        laravel: [ 9.*, 8.* , 10.*]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: 10.*
            testbench: ^8.0
          - laravel: 8.*
            testbench: ^6.23
            larastan: ^1.0
          - laravel: 9.*
            testbench: 7.*
            larastan: ^1.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, redis
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nunomaduro/larastan:${{ matrix.larastan }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
        env:
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
